"""initial_schema

Revision ID: 7a4a43c42b2d
Revises:
Create Date: 2026-07-20 12:29:52.179475

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a4a43c42b2d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("name", sa.TEXT(), nullable=True),
        sa.Column("email", sa.TEXT(), nullable=True),
        sa.Column("region", sa.TEXT(), nullable=True),
        sa.Column("signup_date", sa.TEXT(), nullable=True),
        sa.Column("lifetime_value", sa.REAL(), nullable=True),
        sa.Column("orders_count", sa.INTEGER(), nullable=True),
        sa.Column("segment", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "website_analytics",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("date", sa.TEXT(), nullable=True),
        sa.Column("page_views", sa.INTEGER(), nullable=True),
        sa.Column("unique_visitors", sa.INTEGER(), nullable=True),
        sa.Column("bounce_rate", sa.REAL(), nullable=True),
        sa.Column("avg_session_duration", sa.REAL(), nullable=True),
        sa.Column("conversions", sa.INTEGER(), nullable=True),
        sa.Column("revenue", sa.REAL(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sales",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("date", sa.TEXT(), nullable=True),
        sa.Column("region", sa.TEXT(), nullable=True),
        sa.Column("product_category", sa.TEXT(), nullable=True),
        sa.Column("product_name", sa.TEXT(), nullable=True),
        sa.Column("quantity", sa.INTEGER(), nullable=True),
        sa.Column("unit_price", sa.REAL(), nullable=True),
        sa.Column("total_revenue", sa.REAL(), nullable=True),
        sa.Column("cost", sa.REAL(), nullable=True),
        sa.Column("profit", sa.REAL(), nullable=True),
        sa.Column("customer_segment", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
